theme: jekyll-theme-cayman
title: "Web Coding for Beginners: Population Graphs"
description: "Join this MOOC by Sympa to build a working web app which visualizes population graphs for countries. In one day. With zero coding experience."
