theme: jekyll-theme-cayman
title: "Web Coding for Beginners: Population Graphs"
description: "Build a working web app to visualize population graphs for countries. In one day. With zero coding experience."
